export const themeMap = {
  pink: {
    bg: 'bg-pink-50',
    header: 'bg-pink-100',
    border: 'border-pink-200',
    text: 'text-pink-700',
    hover: 'hover:bg-pink-50',
    dayBg: 'bg-pink-200',
    dayText: 'text-pink-700',
    dayInnerBg: 'bg-pink-100',
  },
  blue: {
    bg: 'bg-blue-50',
    header: 'bg-blue-100',
    border: 'border-blue-200',
    text: 'text-blue-700',
    hover: 'hover:bg-blue-50',
    dayBg: 'bg-blue-200',
    dayText: 'text-blue-700',
    dayInnerBg: 'bg-blue-100',
  },
  green: {
    bg: 'bg-green-50',
    header: 'bg-green-100',
    border: 'border-green-200',
    text: 'text-green-700',
    hover: 'hover:bg-green-50',
    dayBg: 'bg-green-200',
    dayText: 'text-green-700',
    dayInnerBg: 'bg-green-100',
  },
  beige: {
    bg: 'bg-[#F9F5EF]',
    header: 'bg-[#EADDC8]',
    border: 'border-[#D8C7B3]',
    text: 'text-[#5A4C3C]',
    hover: 'hover:bg-[#EFE8DB]',
    dayBg: 'bg-[#EADDC8]',
    dayText: 'text-[#5A4C3C]',
    dayInnerBg: 'bg-[#F1E8DC]',
  },
};
